UsageConfig.py: fix crash when changing timesync option
chronyStatusFinished() does not belong to a class.

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/Console.py", line 49, in finishedCB
    callback(data, retval, self.extra_args)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InitUsageConfig.<locals>.chronyStatusFinished() missing 1 required positional argument: 'action'