enigma2.yml: Update to Ubuntu 24.04
Turn errors into warning.
To bypass commit:
https://github.com/OpenPLi/enigma2/commit/c1daca95800d98ad83b7605b3ea0e7c8fdee2a67

And fix errors(turning error into warning):

dvb/sec.cpp:1298:40: error: storing the address of local variable ‘lnb’ in ‘*this.eDVBSatelliteEquipmentControl::m_curSat.std::
_Rb_tree_iterator<std::pair<const int, eDVBSatelliteSwitchParameters> >::_M_node’ [-Werror=dangling-pointer=]
 1298 |         m_curSat = lnb.m_satellites.end();

../lib/dvb/sec.h:244:7: error: ‘lnb.eDVBSatelliteLNBParameters::guard_offset’ may be used uninitialized [-Werror=maybe-uninitialized]
  244 | class eDVBSatelliteLNBParameters
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~